/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakeHomeSalaryRouteImport } from './routes/take-home-salary'
import { Route as StateRouteImport } from './routes/state'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as RoleRouteImport } from './routes/role'
import { Route as PensionArrearRouteImport } from './routes/pension-arrear'
import { Route as PensionRouteImport } from './routes/pension'
import { Route as PayLevelRouteImport } from './routes/pay-level'
import { Route as PayFixationRouteImport } from './routes/pay-fixation'
import { Route as NpsCalculatorRouteImport } from './routes/nps-calculator'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LtcPlannerRouteImport } from './routes/ltc-planner'
import { Route as IncomeTaxCalculatorRouteImport } from './routes/income-tax-calculator'
import { Route as HraCalculatorRouteImport } from './routes/hra-calculator'
import { Route as GratuityCalculatorRouteImport } from './routes/gratuity-calculator'
import { Route as FitmentSimulatorRouteImport } from './routes/fitment-simulator'
import { Route as EpfCalculatorRouteImport } from './routes/epf-calculator'
import { Route as DaCalculatorRouteImport } from './routes/da-calculator'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ArrearRouteImport } from './routes/arrear'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StateIndexRouteImport } from './routes/state.index'
import { Route as RoleIndexRouteImport } from './routes/role.index'
import { Route as PayLevelIndexRouteImport } from './routes/pay-level.index'
import { Route as StateStateRouteImport } from './routes/state.$state'
import { Route as RoleRoleRouteImport } from './routes/role.$role'
import { Route as PayLevelLevelRouteImport } from './routes/pay-level.$level'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TakeHomeSalaryRoute = TakeHomeSalaryRouteImport.update({
  id: '/take-home-salary',
  path: '/take-home-salary',
  getParentRoute: () => rootRouteImport,
} as any)
const StateRoute = StateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const PensionArrearRoute = PensionArrearRouteImport.update({
  id: '/pension-arrear',
  path: '/pension-arrear',
  getParentRoute: () => rootRouteImport,
} as any)
const PensionRoute = PensionRouteImport.update({
  id: '/pension',
  path: '/pension',
  getParentRoute: () => rootRouteImport,
} as any)
const PayLevelRoute = PayLevelRouteImport.update({
  id: '/pay-level',
  path: '/pay-level',
  getParentRoute: () => rootRouteImport,
} as any)
const PayFixationRoute = PayFixationRouteImport.update({
  id: '/pay-fixation',
  path: '/pay-fixation',
  getParentRoute: () => rootRouteImport,
} as any)
const NpsCalculatorRoute = NpsCalculatorRouteImport.update({
  id: '/nps-calculator',
  path: '/nps-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LtcPlannerRoute = LtcPlannerRouteImport.update({
  id: '/ltc-planner',
  path: '/ltc-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeTaxCalculatorRoute = IncomeTaxCalculatorRouteImport.update({
  id: '/income-tax-calculator',
  path: '/income-tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const HraCalculatorRoute = HraCalculatorRouteImport.update({
  id: '/hra-calculator',
  path: '/hra-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const GratuityCalculatorRoute = GratuityCalculatorRouteImport.update({
  id: '/gratuity-calculator',
  path: '/gratuity-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FitmentSimulatorRoute = FitmentSimulatorRouteImport.update({
  id: '/fitment-simulator',
  path: '/fitment-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const EpfCalculatorRoute = EpfCalculatorRouteImport.update({
  id: '/epf-calculator',
  path: '/epf-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DaCalculatorRoute = DaCalculatorRouteImport.update({
  id: '/da-calculator',
  path: '/da-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrearRoute = ArrearRouteImport.update({
  id: '/arrear',
  path: '/arrear',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateIndexRoute = StateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StateRoute,
} as any)
const RoleIndexRoute = RoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoleRoute,
} as any)
const PayLevelIndexRoute = PayLevelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayLevelRoute,
} as any)
const StateStateRoute = StateStateRouteImport.update({
  id: '/$state',
  path: '/$state',
  getParentRoute: () => StateRoute,
} as any)
const RoleRoleRoute = RoleRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => RoleRoute,
} as any)
const PayLevelLevelRoute = PayLevelLevelRouteImport.update({
  id: '/$level',
  path: '/$level',
  getParentRoute: () => PayLevelRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrear': typeof ArrearRoute
  '/blog': typeof BlogRouteWithChildren
  '/da-calculator': typeof DaCalculatorRoute
  '/epf-calculator': typeof EpfCalculatorRoute
  '/fitment-simulator': typeof FitmentSimulatorRoute
  '/gratuity-calculator': typeof GratuityCalculatorRoute
  '/hra-calculator': typeof HraCalculatorRoute
  '/income-tax-calculator': typeof IncomeTaxCalculatorRoute
  '/ltc-planner': typeof LtcPlannerRoute
  '/mcp': typeof McpRoute
  '/nps-calculator': typeof NpsCalculatorRoute
  '/pay-fixation': typeof PayFixationRoute
  '/pay-level': typeof PayLevelRouteWithChildren
  '/pension': typeof PensionRoute
  '/pension-arrear': typeof PensionArrearRoute
  '/role': typeof RoleRouteWithChildren
  '/salary': typeof SalaryRoute
  '/state': typeof StateRouteWithChildren
  '/take-home-salary': typeof TakeHomeSalaryRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pay-level/$level': typeof PayLevelLevelRoute
  '/role/$role': typeof RoleRoleRoute
  '/state/$state': typeof StateStateRoute
  '/pay-level/': typeof PayLevelIndexRoute
  '/role/': typeof RoleIndexRoute
  '/state/': typeof StateIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrear': typeof ArrearRoute
  '/blog': typeof BlogRouteWithChildren
  '/da-calculator': typeof DaCalculatorRoute
  '/epf-calculator': typeof EpfCalculatorRoute
  '/fitment-simulator': typeof FitmentSimulatorRoute
  '/gratuity-calculator': typeof GratuityCalculatorRoute
  '/hra-calculator': typeof HraCalculatorRoute
  '/income-tax-calculator': typeof IncomeTaxCalculatorRoute
  '/ltc-planner': typeof LtcPlannerRoute
  '/mcp': typeof McpRoute
  '/nps-calculator': typeof NpsCalculatorRoute
  '/pay-fixation': typeof PayFixationRoute
  '/pension': typeof PensionRoute
  '/pension-arrear': typeof PensionArrearRoute
  '/salary': typeof SalaryRoute
  '/take-home-salary': typeof TakeHomeSalaryRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pay-level/$level': typeof PayLevelLevelRoute
  '/role/$role': typeof RoleRoleRoute
  '/state/$state': typeof StateStateRoute
  '/pay-level': typeof PayLevelIndexRoute
  '/role': typeof RoleIndexRoute
  '/state': typeof StateIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrear': typeof ArrearRoute
  '/blog': typeof BlogRouteWithChildren
  '/da-calculator': typeof DaCalculatorRoute
  '/epf-calculator': typeof EpfCalculatorRoute
  '/fitment-simulator': typeof FitmentSimulatorRoute
  '/gratuity-calculator': typeof GratuityCalculatorRoute
  '/hra-calculator': typeof HraCalculatorRoute
  '/income-tax-calculator': typeof IncomeTaxCalculatorRoute
  '/ltc-planner': typeof LtcPlannerRoute
  '/mcp': typeof McpRoute
  '/nps-calculator': typeof NpsCalculatorRoute
  '/pay-fixation': typeof PayFixationRoute
  '/pay-level': typeof PayLevelRouteWithChildren
  '/pension': typeof PensionRoute
  '/pension-arrear': typeof PensionArrearRoute
  '/role': typeof RoleRouteWithChildren
  '/salary': typeof SalaryRoute
  '/state': typeof StateRouteWithChildren
  '/take-home-salary': typeof TakeHomeSalaryRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pay-level/$level': typeof PayLevelLevelRoute
  '/role/$role': typeof RoleRoleRoute
  '/state/$state': typeof StateStateRoute
  '/pay-level/': typeof PayLevelIndexRoute
  '/role/': typeof RoleIndexRoute
  '/state/': typeof StateIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrear'
    | '/blog'
    | '/da-calculator'
    | '/epf-calculator'
    | '/fitment-simulator'
    | '/gratuity-calculator'
    | '/hra-calculator'
    | '/income-tax-calculator'
    | '/ltc-planner'
    | '/mcp'
    | '/nps-calculator'
    | '/pay-fixation'
    | '/pay-level'
    | '/pension'
    | '/pension-arrear'
    | '/role'
    | '/salary'
    | '/state'
    | '/take-home-salary'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/pay-level/$level'
    | '/role/$role'
    | '/state/$state'
    | '/pay-level/'
    | '/role/'
    | '/state/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrear'
    | '/blog'
    | '/da-calculator'
    | '/epf-calculator'
    | '/fitment-simulator'
    | '/gratuity-calculator'
    | '/hra-calculator'
    | '/income-tax-calculator'
    | '/ltc-planner'
    | '/mcp'
    | '/nps-calculator'
    | '/pay-fixation'
    | '/pension'
    | '/pension-arrear'
    | '/salary'
    | '/take-home-salary'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/pay-level/$level'
    | '/role/$role'
    | '/state/$state'
    | '/pay-level'
    | '/role'
    | '/state'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/arrear'
    | '/blog'
    | '/da-calculator'
    | '/epf-calculator'
    | '/fitment-simulator'
    | '/gratuity-calculator'
    | '/hra-calculator'
    | '/income-tax-calculator'
    | '/ltc-planner'
    | '/mcp'
    | '/nps-calculator'
    | '/pay-fixation'
    | '/pay-level'
    | '/pension'
    | '/pension-arrear'
    | '/role'
    | '/salary'
    | '/state'
    | '/take-home-salary'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/pay-level/$level'
    | '/role/$role'
    | '/state/$state'
    | '/pay-level/'
    | '/role/'
    | '/state/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrearRoute: typeof ArrearRoute
  BlogRoute: typeof BlogRouteWithChildren
  DaCalculatorRoute: typeof DaCalculatorRoute
  EpfCalculatorRoute: typeof EpfCalculatorRoute
  FitmentSimulatorRoute: typeof FitmentSimulatorRoute
  GratuityCalculatorRoute: typeof GratuityCalculatorRoute
  HraCalculatorRoute: typeof HraCalculatorRoute
  IncomeTaxCalculatorRoute: typeof IncomeTaxCalculatorRoute
  LtcPlannerRoute: typeof LtcPlannerRoute
  McpRoute: typeof McpRoute
  NpsCalculatorRoute: typeof NpsCalculatorRoute
  PayFixationRoute: typeof PayFixationRoute
  PayLevelRoute: typeof PayLevelRouteWithChildren
  PensionRoute: typeof PensionRoute
  PensionArrearRoute: typeof PensionArrearRoute
  RoleRoute: typeof RoleRouteWithChildren
  SalaryRoute: typeof SalaryRoute
  StateRoute: typeof StateRouteWithChildren
  TakeHomeSalaryRoute: typeof TakeHomeSalaryRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/take-home-salary': {
      id: '/take-home-salary'
      path: '/take-home-salary'
      fullPath: '/take-home-salary'
      preLoaderRoute: typeof TakeHomeSalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state': {
      id: '/state'
      path: '/state'
      fullPath: '/state'
      preLoaderRoute: typeof StateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pension-arrear': {
      id: '/pension-arrear'
      path: '/pension-arrear'
      fullPath: '/pension-arrear'
      preLoaderRoute: typeof PensionArrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pension': {
      id: '/pension'
      path: '/pension'
      fullPath: '/pension'
      preLoaderRoute: typeof PensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-level': {
      id: '/pay-level'
      path: '/pay-level'
      fullPath: '/pay-level'
      preLoaderRoute: typeof PayLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-fixation': {
      id: '/pay-fixation'
      path: '/pay-fixation'
      fullPath: '/pay-fixation'
      preLoaderRoute: typeof PayFixationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nps-calculator': {
      id: '/nps-calculator'
      path: '/nps-calculator'
      fullPath: '/nps-calculator'
      preLoaderRoute: typeof NpsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ltc-planner': {
      id: '/ltc-planner'
      path: '/ltc-planner'
      fullPath: '/ltc-planner'
      preLoaderRoute: typeof LtcPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-tax-calculator': {
      id: '/income-tax-calculator'
      path: '/income-tax-calculator'
      fullPath: '/income-tax-calculator'
      preLoaderRoute: typeof IncomeTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hra-calculator': {
      id: '/hra-calculator'
      path: '/hra-calculator'
      fullPath: '/hra-calculator'
      preLoaderRoute: typeof HraCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratuity-calculator': {
      id: '/gratuity-calculator'
      path: '/gratuity-calculator'
      fullPath: '/gratuity-calculator'
      preLoaderRoute: typeof GratuityCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitment-simulator': {
      id: '/fitment-simulator'
      path: '/fitment-simulator'
      fullPath: '/fitment-simulator'
      preLoaderRoute: typeof FitmentSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epf-calculator': {
      id: '/epf-calculator'
      path: '/epf-calculator'
      fullPath: '/epf-calculator'
      preLoaderRoute: typeof EpfCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/da-calculator': {
      id: '/da-calculator'
      path: '/da-calculator'
      fullPath: '/da-calculator'
      preLoaderRoute: typeof DaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrear': {
      id: '/arrear'
      path: '/arrear'
      fullPath: '/arrear'
      preLoaderRoute: typeof ArrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/': {
      id: '/state/'
      path: '/'
      fullPath: '/state/'
      preLoaderRoute: typeof StateIndexRouteImport
      parentRoute: typeof StateRoute
    }
    '/role/': {
      id: '/role/'
      path: '/'
      fullPath: '/role/'
      preLoaderRoute: typeof RoleIndexRouteImport
      parentRoute: typeof RoleRoute
    }
    '/pay-level/': {
      id: '/pay-level/'
      path: '/'
      fullPath: '/pay-level/'
      preLoaderRoute: typeof PayLevelIndexRouteImport
      parentRoute: typeof PayLevelRoute
    }
    '/state/$state': {
      id: '/state/$state'
      path: '/$state'
      fullPath: '/state/$state'
      preLoaderRoute: typeof StateStateRouteImport
      parentRoute: typeof StateRoute
    }
    '/role/$role': {
      id: '/role/$role'
      path: '/$role'
      fullPath: '/role/$role'
      preLoaderRoute: typeof RoleRoleRouteImport
      parentRoute: typeof RoleRoute
    }
    '/pay-level/$level': {
      id: '/pay-level/$level'
      path: '/$level'
      fullPath: '/pay-level/$level'
      preLoaderRoute: typeof PayLevelLevelRouteImport
      parentRoute: typeof PayLevelRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PayLevelRouteChildren {
  PayLevelLevelRoute: typeof PayLevelLevelRoute
  PayLevelIndexRoute: typeof PayLevelIndexRoute
}

const PayLevelRouteChildren: PayLevelRouteChildren = {
  PayLevelLevelRoute: PayLevelLevelRoute,
  PayLevelIndexRoute: PayLevelIndexRoute,
}

const PayLevelRouteWithChildren = PayLevelRoute._addFileChildren(
  PayLevelRouteChildren,
)

interface RoleRouteChildren {
  RoleRoleRoute: typeof RoleRoleRoute
  RoleIndexRoute: typeof RoleIndexRoute
}

const RoleRouteChildren: RoleRouteChildren = {
  RoleRoleRoute: RoleRoleRoute,
  RoleIndexRoute: RoleIndexRoute,
}

const RoleRouteWithChildren = RoleRoute._addFileChildren(RoleRouteChildren)

interface StateRouteChildren {
  StateStateRoute: typeof StateStateRoute
  StateIndexRoute: typeof StateIndexRoute
}

const StateRouteChildren: StateRouteChildren = {
  StateStateRoute: StateStateRoute,
  StateIndexRoute: StateIndexRoute,
}

const StateRouteWithChildren = StateRoute._addFileChildren(StateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrearRoute: ArrearRoute,
  BlogRoute: BlogRouteWithChildren,
  DaCalculatorRoute: DaCalculatorRoute,
  EpfCalculatorRoute: EpfCalculatorRoute,
  FitmentSimulatorRoute: FitmentSimulatorRoute,
  GratuityCalculatorRoute: GratuityCalculatorRoute,
  HraCalculatorRoute: HraCalculatorRoute,
  IncomeTaxCalculatorRoute: IncomeTaxCalculatorRoute,
  LtcPlannerRoute: LtcPlannerRoute,
  McpRoute: McpRoute,
  NpsCalculatorRoute: NpsCalculatorRoute,
  PayFixationRoute: PayFixationRoute,
  PayLevelRoute: PayLevelRouteWithChildren,
  PensionRoute: PensionRoute,
  PensionArrearRoute: PensionArrearRoute,
  RoleRoute: RoleRouteWithChildren,
  SalaryRoute: SalaryRoute,
  StateRoute: StateRouteWithChildren,
  TakeHomeSalaryRoute: TakeHomeSalaryRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
